westerndigitalcorporation/zenfs

util/zenfs.cc

During our tests on zoned block devices, we need to monitor the database by copying out info logs from ZNS ssd. Original zenfs tool could only backup the whole disk rather than single file or directory, so I add couple few lines of codes to achieve that.

Enable to back up single file or directory

---

util/README.md
util/zen-dump.py

This PR adds metadata analysis tool.
Should be merged after https://github.com/westerndigitalcorporation/zenfs/pull/26
See usage instruction [here](https://github.com/westerndigitalcorporation/zenfs/blob/b4fbf9ab39010f669b3309245b4ee24054ff9279/util/README.md)

util: add metadata analysis tool

---

fs/fs_zenfs.cc
util/zenfs.cc

format the path provided by user, to list files.

utils: format path for listing files

---

fs/fs_zenfs.cc
util/zenfs.cc

Fixed leak in 'ZenFS::MkFS()' caused by a 'Superblock' allocated on
heap and never deallocated.
Fixed resource leak in 'ListZenFileSystems()' where 'opendir()' did not
have corresponding 'closedir()'
Reworked 'zbd_open()' and 'zenfs_mount()' functions so that they now
accept/return 'std::unique_ptr's for 'ZonedBlockDevice' and 'ZenFS'
instead of raw pointers. This fixed a number of memory leaks in
'zenfs' utility command handlers.
Fixed 'std::string's passed by value instead of by const reference in
some function signatures.
Signed-off-by: Yura Sorokin <yura.sorokin@percona.com>

util: fixed memory leaks in zenfs utility

---

README.md
fs/io_zenfs.cc
util/zenfs.cc

Also, updated clang-formatting instructions in the 'README.md'.
Signed-off-by: Yura Sorokin <yura.sorokin@percona.com>

ci: clang-formatted zenfs utility code

---

README.md
util/zenfs.8

Addressed previous comments regarding the licensing information.

Zenfs docs

---

.gitignore

Add make dependency files to gitignore.

---

.github/workflows/smoke-test.yaml
tests/run.sh

Add a github action to run the ZenFS smoke tests.

CI smoke test

---

tests/run.sh

It's useful to know how long a test runs, both for scheduling
testing and to compare different runs to look for regressions
and improvements in execution time.
So, print the time it takes to run each test and the total
time to run a whole test set in run.sh. Also store the time in the results
directory for comparing different runs.

tests: print and store time spent for tests and test sets

---

fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

Suggestion for fix fix for #68

Do not silently ignore zone close errors

---

util/zenfs.cc

Presently aux-dir is created at mount time, but it should be
created at mkfs time. During mkfs, create aux-dir if it is not present.
Check if it is empty and accessible by the user, else error out.
Signed-off-by: Aravind Ramesh <Aravind.Ramesh@wdc.com>

util: zenfs mkfs does not create the aux-dir immediately

---

fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

Add a method to close the active zone.

fs: Refactor `ZoneFile` for code reuse

---

.github/workflows/zbdbench.yaml

Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

ci: zbdbench workflow

---

.github/workflows/zbdbench.yaml

ci: Fix pulling ZenFS for zbdbench CI action.

---

fs/zbd_zenfs.cc

We could run into a situation where all zones are empty or full except busy ones.
In such cases, the `FinishCheapest` could return an error of failing to find a victim, but I believe we should keep trying until we get an active zone.

zbd: Allow FinishCheapestZone to fail without break the zone allocation

---

.github/workflows/cpp-lint.yaml
.github/workflows/smoke-test.yaml
fs/zbd_zenfs.cc

Reported-by: Yura Sorokin <yura.sorokin@percona.com>
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

fs: Fix use of uninitialized value in `ZonedBlockDevice` destructor

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/zbd_zenfs.cc
util/zenfs.cc

This PR picks two fixes from the 1.0.x branch

Cherry-pick fixes from 1.0.x branch to master

---

fs/io_zenfs.cc

If the active zone is released and the file has not been marked
up as closed (active extent = NO_EXTENT) the file recovery
process will try to recover everything up to the active extents
zone write pointer, which might contain data from other files.
To make sure this does not happen, mark up the file as closed
before releasing the active zone.

fs: ensure that metadata is persisted before releasing active zone

---

fs/fs_zenfs.cc
util/zenfs.cc

This pull request overhauls the path handling for backup, restore and list, addressing the issues listed in:
https://jira.percona.com/projects/WDCZEN/issues/WDCZEN-26
The PR also contains a patch for removing some leftover debug prints during restore.

zenfs util backup/restore fixes (for V1 branch)

---

fs/fs_zenfs.cc
util/zenfs.cc

This is a PR to lift the fixes already merged to the V1 branch as part of  https://github.com/westerndigitalcorporation/zenfs/pull/146

Backup/restore fixes (for master) 

---

util/zenfs.8
util/zenfs.cc

Added 2 more commands to zenfs utility.
1. link - creates a hardlink
2. delete  - deletes specified file
These commands can be helpful for unit testing and debugging.
These are good to have features.

Zenfs cmds

---

.github/workflows/long-performance-xfs.yaml
.github/workflows/long-performance.yaml
.github/workflows/rocks-nightly.yaml
.github/workflows/short-performance-xfs.yaml
.github/workflows/short-performance.yaml
.github/workflows/smoke-test-debug.yaml
.github/workflows/smoke-test.yaml
.github/workflows/zbdbench.yaml

ci: Checkout `zbdbench` from github

---

fs/zbd_zenfs.cc

In Zone::Append, the pwrite is changed to use left instead of size as the buffer size.
In ZonedBlockDevice::DirectRead, logic has been changed to the same approach as in other
places in the code, where the number of bytes left is tracked and buffer pointers and
offsets are adjusted with the bytes already read.
Signed-off-by: Jorgen S. Hansen <jorgen.hansen@wdc.com>
Closes #181

zbd: Fix partial I/O handling in Append and DirectRead

---

util/zenfs.cc

zenfs util allows only directories to be restored, but backup
command allows single file backups, so this makes the
restore behavior consistent with backup command regarding
single file backup/restore.

util: Allow restore of single files in to ZenFS.

---

fs/fs_zenfs.cc
fs/io_zenfs.cc
fs/io_zenfs.h

Prevent concurrent write opens/migrations 

---

tests/run.sh

Add some hooks to allow for arbitrary pre/post commands to be run for each tests and for copying rocksdb LOG files (useful for checking write stats in read-while-writing tests that does not include the write IOPS for example)

Test runner improvements

---

.github/workflows/mtr-test.yaml

ci: Fast-forward percona-server release for MTR test case

---

.github/workflows/percona-server-smoke-test.yaml

Nightly for master, on PR for release branches.

Percona server smoke tests

---

.github/workflows/cpp-lint.yaml
fs/zbd_zenfs.cc

Fixes up the lint check ci and the subject for the patch submitted in #250

Segfault pr fixup
