westerndigitalcorporation/zenfs

.gitignore
fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h
util/zenfs.cc

This pull requests adds a bunch of improvements and bug fixes, see commit messages below
```
commit 93b112c52c69ea0ccc715bc5cc76f5de3b1a6f17 
Author: Hans Holmberg <hans.holmberg@wdc.com>
Date:   Thu Mar 25 15:06:10 2021 +0000
Dissallow deletes of files open for writing
We don't support deleting files open for writing,
so return an error if rocksdb tries to do this.
commit 891a65339de4596f796e5745cc0b20b39f5b6ef5
Author: Hans Holmberg <hans.holmberg@wdc.com>
Date:   Thu Mar 18 12:34:44 2021 +0000
Add object files to gitignore
commit 094c270df993330b0b1a3b6e870a5859adcdd6c2
Author: Hans Holmberg <hans.holmberg@wdc.com>
Date:   Fri Mar 12 10:43:05 2021 +0000
Enable read-only mounting …
```

A slew of improvements and bugfixes

---

fs/fs_zenfs.cc

We're not persisting file records until we get a sync or the
file is closed. This has been observed to cause problems
when recreating the file system state (delete records
of files that does not have an earlier file record in
the meta log)
The above issue has been seen during unclean shutdowns
of rocksdb(reboots, crashes).
Remove the possibility log inconsistency by persisting
a file record when a writable file is created - this
seems to be the right thing to do anyway.

fs: persist a file record on file creation

---

fs/zbd_zenfs.cc
fs/zbd_zenfs.h
util/zenfs.cc

```
$ sudo ./zenfs mkfs --zbd=nvme0n1 --aux-path=/tmp/zenfs-aux --force
INFO: For ZBD /dev/nvme0n1, setting scheduler to mq-deadline.
ZenFS file system created. Free space: 3970899 MB
```
```
$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench
67457871    000043.sst
67456489    000080.sst
67455822    000117.sst
67457826    000154.sst
67456048    000191.sst
67455714    000228.sst
67456436    000266.sst
67455873    000294.sst
67457790    000331.sst
67455988    000368.sst
67455714    000405.sst
67456451    000442.sst
67455755    000480.sst
67457827    000518.sst
67456007    000546.sst
67455832    000583.sst
67456482    000620.sst
67455819    000657.sst
67457813    000694.sst
67456079    000732.sst
67455727    000770.sst
67456442    000808.sst
```

Zenfs updates

---

fs/fs_zenfs.cc
fs/io_zenfs.cc
fs/zbd_zenfs.cc

commit 548ca5dc65b9f6ca75fc8104518ad15325d1374c
Author: Hans Holmberg <hans.holmberg@wdc.com>
Date:   Thu Apr 29 08:52:19 2021 +0000
fs: align buffers properly
When submitting direct writes, the buffers should be
page-size aligned, not block-size aligned. Fix this.
commit e423a9355e0f5afea5726d3c71bf1f86e04546da
Author: Hans Holmberg <hans.holmberg@wdc.com>
Date:   Wed Apr 28 08:25:19 2021 +0000
fs: enable direct writes
For some reason, the direct(unbuffered) writes ended up being disabled
in the initial commit of the project. Re-enable this, as it lowers
cpu overhead and should have performance benifits when enabled.

Write buffer fixes

---

.gitignore
tests/get_good_db_bench_params_for_zenfs.sh
tests/long_performance/0000_fillrandom.sh
tests/long_performance/0001_overwrite.sh
tests/long_performance/0002_readwhilewriting_ratelimit.sh
tests/long_performance/common.sh
tests/quick_performance/0000_fillseq.sh
tests/quick_performance/0001_fillrandom.sh
tests/run.sh
tests/smoke/0000_fillseq.sh
tests/smoke/0001_fillrandom.sh
tests/smoke/0002_overwrite.sh
tests/smoke/0003_readwhilewriting.sh
tests/smoke/0004_dbstress.sh
tests/smoke/common.sh

Add a simple testing framework inspired by xfstests / blktests and a test
suite for minimal smoke testing running some db bench workloads and a short
db_stress test.
Tests can be run on normal filesystems and zenfs.
A run script can runs a set of tests in a subdirectory.
./run.sh <name of test> <test subdirectory>
Example command lines for the run.sh script:
FS_PARAMS="--fs_uri=zenfs://dev:nvme3n1" ./run.sh zenfs_testrun smoke
FS_PARAMS="--db=/mnt/xfs/test" ./run.sh xfs_testrun smoke
Stdout results for each test is stored in results/<name of test>/<test suite>
Comparing different runs enables checking performance regressions.
Also, Add two test sets for doing some basic performance testing and
a script that provides a decent base parameter set for testing zenfs
performance.
* The …

Add some simple module-level testing

---

tests/run.sh
tests/utils/0010_mkfs.sh
tests/utils/0020_list.sh
tests/utils/0030_df.sh
tests/utils/0040_backup.sh
tests/utils/0050_restore.sh
tests/utils/common.sh

Adds new tests to test zenfs mkfs, list, df, check scheduler,
backup, restore and post-restore data integrity check.
sudo FS_PARAMS="--fs-uri=zenfs://dev:nvme0n1" ./run.sh util-tests utils
Signed-off-by: Aravind Ramesh <Aravind.Ramesh@wdc.com>

test: add zenfs utility related test cases to test suite.

---

fs/zbd_zenfs.cc

BLKREPORTZONE ioctl expects the user to have read access,
so use the read fd instead of write fd to get the zone
report from the ZNS device.
Signed-off-by: Niklas Cassel <niklas.cassel@wdc.com>
Signed-off-by: Yura Sorokin <yura.sorokin@percona.com>

fs: use read fd when reading zone report from ZNS device

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.h
util/zenfs.cc

Fix the following gcc-11 compilation issues:
```
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc: In member function ‘virtual rocksdb::IOStatus rocksdb::ZenFS::GetChildren(const string&, const rocksdb::IOOptions&, std::vector<std::__cxx11::basic_string<char> >*, rocksdb::IODebugContext*)’:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:532:19: error: loop variable ‘f’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]
532 |   for (const auto f : auxfiles) {
|                   ^
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc: In member function ‘rocksdb::Status rocksdb::ZenFS::Mount(bool)’:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zen …
```

Fix gcc-11 and clang-12 compilation issues

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
util/zenfs.cc

Add a modification time field to zonefiles.
```
$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench
56158    Jun 02 2021 09:17:48            LOG
0    Jun 02 2021 09:17:37            LOCK
417960339    Jun 02 2021 09:17:42            000012.sst
421439677    Jun 02 2021 09:17:45            000017.sst
514117763    Jun 02 2021 09:17:46            000018.log
242565614    Jun 02 2021 09:17:46            000019.sst
267304814    Jun 02 2021 09:17:47            000021.log
16    Jun 02 2021 09:17:37            CURRENT
37    Jun 02 2021 09:17:37            IDENTITY
917    Jun 02 2021 09:17:37            MANIFEST-000004
6143    Jun 02 2021 09:17:37            OPTIONS-000007
```

Modification time

---

fs/zbd_zenfs.h

ZenFS currently handles zones sizes up to 4GB.
Enable zenfs to handle zone sizes more than 4GB.
Signed-off-by: Aravind Ramesh<Aravind.ramesh@wdc.com>

fs: enable zenfs to handle zonesize more than 4GB

---

.clang-format
.github/workflows/cpp-lint.yaml
README.md
fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc

In this PR, we added clang-format lint for this repo. We use Google style, as it requires minimum effort for us to pass clang-format compared with other styles.

ci: add clang-format check

---

fs/fs_zenfs.cc
fs/fs_zenfs.h

If there are two threads concurrently calling DeleteFile, it seems possible that there will be a racing condition. This PR fixes this issue.
https://github.com/westerndigitalcorporation/zenfs/blob/master/fs/fs_zenfs.cc#L391
|             Thread 1                |           Thread 2            | |
| ----- | ---- | ---- |
| zoneFile = GetFile(fname); | zoneFile = GetFile(fname); | // both succeed |
|     files_mtx_.lock();           |     waiting                  | |
|   zoneFile = files_[fname]; |     waiting                  |  // succeed |
|    files_mtx_.unlock();        |    files_mtx_.lock();  | |
|                                              | if (zoneFile != nullptr) | // this check passes although zoneFile might have been deleted |
|                                              | …

fs: only acquire lock once on deletion

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h
util/zenfs.cc

This PR adds dump metadata command. This command will dump all files and extents in json format. After this PR is merged, we will add tools to analyze and visualize the metadata.
Example JSON file (prettified)
```json
{
"zones": {
"meta": [
{
"start": 0,
"capacity": 1129316352,
"max_capacity": 1129316352,
"wp": 0,
"lifetime": 0,
"used_capacity": 0
},
{
"start": 2147483648,
"capacity": 654110720,
"max_capacity": 1129316352,
"wp": 2622689280,
"lifetime": 0,
"used_capacity": 0
},
{
"start": 4294967296,
"capacity": 1129316352,
"max_capacity": 1129316352,
"wp": 4294967296,
"lifetime": 0,
"used_capacity": 0
}
],
"io": [
{
"start": 6442450944,
"capacity": 1126080512,
"max_capacity": 1129316352,
"wp": 6445686784,
"lifetime": 0,
"used_capacity": 719606
},
{
"start": 8589934592,
"capacity": 0, …
```

util: add dump metadata command

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h
util/README.md
util/zen-dump.py
util/zenfs.cc

This commit enhances the efficiency of dump tool. Now it could process several gigabytes of data within a minute. The JSON data is directly piped into stdout instead of being cached in a stringstream. And the analysis script is now using high-performance JSON parser while showing progress when processing data.
Signed-off-by: Alex Chi <iskyzh@gmail.com>

util: enhance dump tool

---

README.md

It seems the instruction in README has errors on description, so I fixed them.

Fix instruction errors in README

---

fs/fs_zenfs.cc
fs/zbd_zenfs.cc
fs/zbd_zenfs.h
util/zenfs.cc

Allow for backing up mounted file systems with a live writer
for testing purposes.
We need some form of snapshots to do this without
risking data corruption/loss, but this is good enough
for now to get zenfs compatible with the mysql/myrocks
mtr tests.
Do this by allowing for non-exclusive block device
access when running the backup command with the --force flag.
A warning is emitted and the the potential data corruption
is documented in the help.
Suggested by Yura Sorokin (in #37 )
Example: (with an active mount by db bench doing writes in another process)
```
$./zenfs backup --zbd=nvme2n1 --path=/tmp/backup_test
Failed to open zoned block device: nvme2n1, error: Invalid argument: Failed to open zoned block device: Device or resource busy
$./zenfs backup --zbd=nvme2n1 …
```

util: allow backups of already mounted filesystems for testing purposes

---

fs/fs_zenfs.cc

On ZenFS empty directories cannot be created, therefore we cannot
distinguish between "Directory not found" and "Directory is empty"
and always return empty lists with OK status in both cases.

fs: fixed problem with ZenFS::GetChildren() returning error for empty directories

---

fs/zbd_zenfs.cc
fs/zbd_zenfs.h

AllocateZone might mistakenly assume fully-written zone
is available to use. This is also an issue caused by a race
condition, and will make AllocateZone return nullptr
in rare cases (but actually might happen once a day when
active zone number is close to limit).
A simple fix is to hold the zone_resources_mtx_ throughout
the CloseWR function, instead of taking it twice inside to
NotifyIOZone{Full|Closed}. Therefore, AllocateZone always sees
a consistent state.
(just added more info from Alex to the commit message)
Signed-off-by: Alex Chi <iskyzh@gmail.com>

fs: consistent view when zone full

---

util/zenfs.cc

Added missing "dump" command in the list of supported ones.
Signed-off-by: Yura Sorokin <yura.sorokin@percona.com>

util: fixed command line help string

---

.github/workflows/cpp-lint.yaml

Only zenfs/fs was being checked earlier,
now all .c/.cc files will be part of the lint check.

ci: add zenfs directory as part of lint check.

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h

Maintain the zonefile objects as a shared pointer to ensure the objects
are not accidentally deleted when it is still held by other users.
Refer issue #51 for details.

fs: ensure ZoneFile object is reference counted

---

README.md
tests/crashtest/0000_whitebox.sh
tests/crashtest/0001_blackbox.sh
tests/crashtest/base-crashtest-call.sh
tests/crashtest/db_crashtest.py
tests/run.sh
tests/zenfs_base_crashtest.sh

Adapt crashtesting for ZenFS from the original [db_crashtest.py]
(https://github.com/facebook/rocksdb/blob/master/tools/db_crashtest.py).
It kills the DB at a random point in time (blackbox) or at predefined places
in the RocksDB code (whitebox) and checks for recovery.
For further reading visit the RocksDB
[wiki](https://github.com/facebook/rocksdb/wiki/Stress-test).
However the goal for ZenFS crashtesting is to cover a specified set of
parameters rather than randomized continuous testing.
Therefore db_crashtest.py is copied and modified to use the parameters of
interest. Additionally convenience and integration scripts for the existing
ZenFS test suite are added.

test: introduce crashtesting

---

.github/workflows/smoke-test.yaml

Docker images pile up on the runner. This patch removes the images after the test has run.
We will move this to the harness eventually, but for now this will have to do.

ci: Remove docker images after run

---

util/Makefile

When libzbd and librocksdb is not living in the same location, it is nice to be able to pass extra flags to the build script.

Allow extra compiler/linker flags when building zenfs utility

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

For non-debug builds failing 'Acquire' and 'Release' calls where not
handled. Passing errors over to the calling function/application.
Reported-by: Hans Holmberg <hans.holmberg@wdc.com>
Suggested-by: Andreas Hindborg <andreas.hindborg@wdc.com>

fs: Handle faulty Acquire and Release calles on zones.

---

fs/fs_zenfs.cc
fs/zbd_zenfs.cc

Make error messages unique for open device errors.

Update error messages raised when open device fail

---

fs/fs_zenfs.cc

Return error when trying to delete non existing file, to align with
`PosixFileSystem::DeleteFile()`:
```c++
if (unlink(fname.c_str()) != 0) {
result = IOError("while unlink() file", fname, errno);
}
```

fs: Correct impl of `ZenFS::DeleteFile` when target does not exist

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/metrics.h
fs/metrics_sample.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h
zenfs.mk

ZenFSMetrics is used to monitor some of the variables on ZenFS in real time.
In addition to this, two other classes have been added to metrics.h.
NoZenFSMetrics is an empty implementation of ZenFSMetrics and is used by default.
ZenFSMetricsLatencyGuard is used to count the execution time of a function,
and it reports the time between construction and destruction to Metrics.
Signed-off-by: Liu Ruicheng <sagitrs67@gmail.com>
Co-authored-by: Andreas Hindborg <andreas@metaspace.dk>
(Rebased the patch and fixed up a few non-debug compilation issues)

fs: Add ZenFSMetrics to ZenFS (REBASED)

---

.github/workflows/smoke-test.yaml
.gitignore
fs/fs_zenfs.cc
fs/fs_zenfs.h
generate-version.sh
util/zenfs.8
util/zenfs.cc
zenfs.mk

When building ZenFS through RocksDB the ZenFS version is updated by
its Makefile and contains the output of `git describe --dirty`.
This means that the version depends on the latest git tag and if
preceding commits exits the latest commit's short hash
(see (documentation)[https://git-scm.com/docs/git-describe]).
The version is regenerated if the git HEAD changed at build time.
Major, minor, patch, the short commit hash and a dirty flag is
persisted within the superblock. A new util command `fs-info` was
added that outputs the contents of the current superblock which
includes the ZenFS version information.
Suggested-by: Andreas Hindborg <andreas.hindborg@wdc.com>

fs, util: Introducing semi automatic versioning for ZenFS.

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/metrics.h
fs/metrics_sample.h
fs/snapshot.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

Getting the state of the ZBD is different from others, for example the ZBD does not intentionally maintain a variable called free_space_, so we need to calculate the free space via a function GetFreeSpace().
Also, sometimes we would like to report these temporarily calculated values through metrics, and it is not a good idea to periodically calculate a variable in a specific function. So we added a ReportSnapshot interface to Metrics and left it up to the debugger to decide when to report them: the user can decide which variables to compute online via SnapshotOptions and then report them one by one via Metrics::ReportSnapshot().
We have added a sample related to this in metrics_example.h.
Signed-off-by: Liu Ruicheng <liuruicheng.222@bytedance.com>

fs: Add support for getting ZBD status.

---

fs/snapshot.h

As our algorithm is updated, snapshot of Zone::used_capacity_ is needed.
Signed-off-by: Liu Ruicheng <liuruicheng.222@bytedance.com>

fs: add supporting for ZoneSnapshot::UsedCapacity().

---

util/zenfs.cc

Some variants of RocksDB (and older RocksDB version) may not have a `plugin` directory, so I am changing the include path a relative one.

zenfs: change include header path to relative path

---

fs/fs_zenfs.cc
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

TerarkDB need to log important information in production mode, so
for Release or RelWithDebInfo build type, we could set log level to
INFO_LEVEL.
Note that we still need to figure out how do reuse RocksDB's logger
in the future, then we could remove these changes.
The garbage stats log helps us understand the garbage distribution of
the disk and also let us know whether the collaborative GC works as
expected.
(fixed up code formatting)

log: enable logger by default and add garbage stats log

---

fs/fs_zenfs.cc
fs/io_zenfs.cc
fs/io_zenfs.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

This pull request reworks the IO Zone allocator to reduce write latencies
Summary of commit messages below:
fs: priortize open resources for WAL to avoid starvation
Reserve one open topen for write ahead log allocation
to avoid WAL writes being stalled due to the compaction
eating up all open resources.
fs: avoid finishes in allocator by relaxing the life time diff requirement
If the write buffer is not big enough to fill a zone, the first-level ssts
will end up as many small files and cause the allocator to finish a lot of zones as the
write life time diff requirement cannot be met.
Avoid the finishes by allowing same-level-ssts to co-locate the same zones
when we're at the max active limit.
Signed-off-by: Hans Holmberg …

Rework allocator to improve write QoS

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h

This PR reduces write tail latency and increases throughput for use cases that require synced writes (db_bench --sync=1 ..)  when all written key/values must be persisted directly and readable after a potenial crash.
The trick is to store the active extent start that we are writing to for each file and use the write pointer to recover the data in case of a crash. For non-block-size aligned writes, like the WAL, a sparse format is introduced where the length of each non-aligned segment is prefixed to the data, so each write contains the valid data length.
With these changes, we only need to write to the metadata zone when we a) allocate a new extent b) close the file.
```
fs: implement file recovery based on active extent information
We can now recover data from files that has not been …
```

Implement inline extents

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.h
fs/metrics.h
fs/metrics_sample.h
fs/snapshot.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

1. Remove unnecessary abstraction, reduce complexity
2. Add extents to file mapping, help us find filename by extent id (useful for collaborative GC)

metrics: refactor metrics, reduce code complexity

---

fs/fs_zenfs.cc

When building with DEBUG_LEVEL=1 with below command,
"make clean;DEBUG_LEVEL=1 ROCKSDB_PLUGINS=zenfs make -j48 db_bench db_stress ldb"
rocksdb compilation fails with error:
"error: ‘std::string rocksdb::GetLogFilename(std::string)’ defined but not used"
Current logic defines the function GetLogFileName() for all debug levels(0,1,2)
but uses it only when debug-level=0. So for debug builds it gets defined but
is not used, resulting in the error. Also logs are enabled in production
builds now. Related to 7f8392e.
Define it such that is enabled for (debug-level > 0) OR when TERARKDB is defined.
Signed-off-by: Aravind Ramesh <Aravind.Ramesh@wdc.com>

fs: build failure when compiling rocksdb in debug mode

---

.github/workflows/cpp-lint.yaml
.github/workflows/smoke-test.yaml
fs/fs_zenfs.cc
fs/fs_zenfs.h
util/zenfs.cc

Change signature of `ListZenFileSystems` to return status by value and file
system list by reference.
Reported-by: Mohit Joshi <mohit.joshi@percona.com>
Reported-by: Yura Sorokin <yura.sorokin@percona.com>
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

 fs,util: Fix a bug where zone locks are not handled correctly

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h

Increase the zone extent size to be 64 bits instead of 32, to
support very large file sizes in large zones.
This change is not backward-compatible with the current on-disk
format, so we need to step up the version.

fs: increase zone extent size to 64 bits

---

fs/zbd_zenfs.h

`Zone::used_capacity_` is signed while `ZoneExtent::length_` is unsigned. This
causes a comparison problem in an assertion. There is no reason for
`used_capacity_` to be signed. This patch changes `Zone::used_capacity_` to
unsigned.
With gcc-9.3.0:
```text
In file included from plugin/zenfs/fs/io_zenfs.cc:11:
plugin/zenfs/fs/io_zenfs.cc: In destructor ‘virtual rocksdb::ZoneFile::~ZoneFile()’:
plugin/zenfs/fs/io_zenfs.cc:243:41: error: comparison of integer expressions of different signedness: ‘std::__atomic_base<long int>::__int_type’ {aka ‘long int’} and ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
243 |     assert(zone && zone->used_capacity_ >= (*e)->length_);
|                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: …
```

fix: Change `used_capacity` to unsigned

---

fs/fs_zenfs.cc
fs/fs_zenfs.h

Addressed the the review comments provided in PR #93.
This is rebased on the latest master branch.

Update the apis ReopenWritableFile() and ReuseWritableFile() in ZenFS.

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h
fs/snapshot.h
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

Please merge this PR first: https://github.com/westerndigitalcorporation/zenfs/pull/122
Please resolve this issue first: https://github.com/westerndigitalcorporation/zenfs/issues/124#issue-1089722934
NOTE:
The latest master branch has a significant performance drawback caused by the `inlined extent header` feature, we should first resolve that problem.
For non KV separation RocksDB, the default GC may work relatively well in most cases.
But for BlobDB(RocksDB's KV separation implement) and TerarkDB, the key files and value files don't have a predictable lifetime like before.
Thus the RocksDB layer's GC could be quite useless in these cases (We could meet 30%~50% garbage when running out of space).  And also, for heavy write throughput, non-kv separation implement could also run out of …

fs: add extent migration API for better collaborative GC

---

fs/fs_zenfs.cc
fs/io_zenfs.cc
fs/metrics.h
fs/metrics_sample.h
fs/zbd_zenfs.cc
zenfs.mk

- The previous metrics implementation is not well documented
- Some metrics helper functions are not necessary (e.g. `ZENFS_LABEL` confuses readers)
- Add QPS and throughput trace for ZoneFile::PositionedAppend
- Add Throughput trace for Zone::Append

metrics: add more metrics explanition comments & refine metrics

---

fs/fs_zenfs.cc

Upstream RocksDB has changed the filesystem registration API.
Add support for the new API and enable compatibility with
older versions of RocksDB (version < 7 ) by passing a compile time
flag (ZENFS_USE_OLD_REGISTRATION_API).
Example(building zenfs with rocksdb 6.x.x after this commit)
CFLAGS=-DZENFS_USE_OLD_REGISTRATION_API ROCKSDB_PLUGINS="zenfs" make db_bench

Make zenfs compatible with latest plugin registration API

---

fs/io_zenfs.cc

We do allow that files can be re-opened for appending
(ReopenWritableFile), so drop the assertion that the
file is empty when creating a new writable file.

fs: drop empty-file assertion for writable files

---

fs/io_zenfs.cc
fs/io_zenfs.h

If a `ZonedWritableFile` is destroyed without being closed, buffered contents
are not flushed to disk. This patch activates close procedure on object
destruction to fix the problem.

fs: Fix a bug where `ZonedWritableFile` bufferes are not flushed

---

fs/io_zenfs.cc

This issue didn't raise up because we always build with RelWithDebInfo, never tested in a debug mode....
```
assert(offset % block_sz != 0);
```

io: fix wrong assertion condition

---

.github/workflows/long-performance-xfs.yaml
.github/workflows/long-performance.yaml
.github/workflows/short-performance-xfs.yaml
.github/workflows/short-performance.yaml
.github/workflows/smoke-test-debug.yaml
.github/workflows/smoke-test.yaml
.github/workflows/zbdbench.yaml
tests/smoke/0004_dbstress.sh
util/Makefile
zenfs.mk

Use `pkg-config` to specify dependencies for ZenFS plugin. Required support was added to RocksDB a while back.

Use `pkg-config` for specifying dependencies.

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
fs/io_zenfs.cc
fs/io_zenfs.h

This api simulates posix hard link behavior.
It accepts the source-file and destination-file names, if the source file is
available, it creates an entry in the in-memory files_ map and also
updates the source-file's metadata about the newly linked file and
increments the link count for the source-file and persists this information
on disk.
File deletion ensures that as long as there are links associated to a file,
the file is not deleted on disk and only link specific metadata is updated
and persisted on disk.

fs: Add LinkFile api support to ZenFS.

---

.github/workflows/long-performance-xfs.yaml
.github/workflows/long-performance.yaml
.github/workflows/mtr-test.yaml
.github/workflows/rocks-nightly.yaml
.github/workflows/short-performance-xfs.yaml
.github/workflows/short-performance.yaml
.github/workflows/smoke-test-debug.yaml
.github/workflows/smoke-test.yaml
.github/workflows/zbdbench.yaml
fs/fs_zenfs.cc
fs/fs_zenfs.h
util/zenfs.8
util/zenfs.cc

These commits enable ZenFS to ZenFS checkpointing in RocksDB.
Renaming was fixed such that all ZenFS file names are renamed according to a directory rename.
The `force-rmdir` util command was introduced so that checkpoints can be deleted (which is also needed by the rocksdb.checkpoint MTR test case). 
Addresses jira issue WDCZEN-19.
Reported-by: Yura Sorokin <yura.sorokin@percona.com>

Support RocksDB checkpointing

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
util/zenfs.cc

It formats input paths lexically, to handle scenarios like
relative paths, superfluous slashes.

fs: format all input paths into ZenFs lexically

---

fs/io_zenfs.cc

Ex: extent_length is 4094, sparse head+data+pad, it needs 2 blocks, not 1
Signed-off-by: hml1006 <hml1006@qq.com>
(fixed up commit message)

fs: Fix extent blocks compute error for sparse recovery

---

fs/io_zenfs.cc

When preparing buffered writes for the next io,
we copy data within the buffer and that may lead
to overlapping memory ranges that is dissallowed
by memcopy. Use memmove instead to fix this.

fs: dont do memcopy with overlapping memory ranges

---

fs/filesystem_utility.h
fs/fs_zenfs.cc
fs/fs_zenfs.h
util/zenfs.cc
zenfs.mk

C++17 was mandatory, since we were using std::filesystem(::path) and
RocksDB also moved on to C++17.
With this commit boost::filesystem replaces std::filesystem if
the C++ std < C++17 when compiling.

fs, util: Use boost libraries for C++ std < C++17

---

fs/fs_zenfs.cc
fs/zbd_zenfs.cc
fs/zbd_zenfs.h

Keep track of how many total bytes that are written and
how many bytes that are moved during garbage collection
to allow for write amp statistics to be calculated.

zbd: add garbage collection stats interface

---

CMakeLists.txt

rocksdb has a guideline for how to integrate with the cmake
build system. Simply provide plugin specific variables with
.cc files and the library requirements.
We run generate_version.sh at cmake time - this should be
ok since any change in the git repo could affect cmake,
and as such cmake should be rerun anyways. Also, with
the current cmake infrastructure in rocksdb, it doesn't
seem to be possible to run generate_version.sh at build
time prior to processing the zenfs source files.
Signed-off-by: Jorgen Hansen <jorgen.hansen@wdc.com>

build: make zenfs work with cmake build

---

fs/filesystem_utility.h

This PR fixes a verification error that occurred when executing db_stress (RocksDB v6.29.5):
```
./db_stress --ops_per_thread=1000 --reopen=5 --db=dbname --fs-uri=zenfs://dev:nvmeXnX --read_fault_one_in=0
```
<del>When boost::filesystem is enabled instead of filesystem_utility.h the "fs: Do not prepend path with '/' in `FormatPathLexically`" commit is necessary otherwise executing db_stress will end in the following error:
`open error: IO error: RenameLink: Failed to find the linked file`</del>
<del>If filesystem_utility.h is enabled the "fs: Do not prepend path with '/' in `FormatPathLexically`" commit is not strictly necessary.</del>

db_stress verification

---

README.md
fs/fs_zenfs.cc
fs/metrics_prometheus.cc
fs/metrics_prometheus.h
zenfs.mk

Set environment variable ZENFS_EXPORT_PROMETHEUS=y when building to enable
prometheus export of metrics. Exporter will listen on 127.0.0.1:8080.
Requires prometheus-cpp-pull == 1.1.0.

fs: Add metrics prometheus exporter

---

fs/zbd_zenfs.cc
fs/zonefs_zenfs.h

Fix the broken c++11 builds by open-coding make_unique (c++14)
and include the <list> header.

fs: make zenfs compile with c++11 again

---

fs/fs_zenfs.cc
fs/fs_zenfs.h

External callers of NewZenFS may not be aware of the zonefs support, so make a shim that converts from the "old" signature to the new one.
Signed-off-by: Jorgen Hansen <jorgen.hansen@wdc.com>

fs: Provide shim for NewZenFS calls that don't know about zonefs

---

CMakeLists.txt

Introduce an environment variable check that makes it possible to skip the libzbd check in cases where libzbd isn't provided througha package.
Signed-off-by: Jorgen Hansen <jorgen.hansen@wdc.com>

cmake: Make it possible to skip libzbd check

---

util/zenfs.cc

Replace the pattern where back() might be called on an empty string with the AddDirSeparatorAtEnd fuction which was fixed in a previours commit:
`util: Fix AddDirSeparatorAtEnd where back() can not be called on an empty string`

util: Fix occurances where back() might be called on an empty string

---

util/zenfs.cc

Replace the pattern where back() might be called on an empty string with the AddDirSeparatorAtEnd fuction which was fixed in a previours commit:
`util: Fix AddDirSeparatorAtEnd where back() can not be called on an empty string`

Backport `util: Fix occurances where back() might be called on an empty string`

---

fs/fs_zenfs.cc
fs/io_zenfs.cc

Observed that when heavy workloads are running(like sysbench) on zenfs, commands like "zenfs df/list" would error out with below error log. "Unexexpeted extent length while recovering".
When mounted in read-only mode, the process mounting it is understood to not make any changes to the filesystem. So it is better to do a repair() when the process has the intent to write data/metadata (write mode mount). Also when mounted in read-only mode(by say zenfs list), there could be write happening by RocksDB which can alter the data/metadata state and doing a repair at that time in a read-only mount state is also not warranted.
So do repair when mounted with write permission.

zenfs: Do not Repair() when the mount is read-only mode.

---

fs/fs_zenfs.cc
fs/fs_zenfs.h
util/zenfs.cc

Add an option to enable garbage collection in zenfs.
The garbage collection, if enabled, kicks in under 20% capacity left and cleans out zones with 1% valid data in them to start off with, increasing to 40% at 99% capacity.
This scheme reduces space amplification down to as little as 5% (from ~10-15%) in my testing.

Garbage collection

---

fs/fs_zenfs.cc

Fix the following issue using the same approach as fixes in RocksDB:
```
/data/mysql-server/percona-8.0/storage/rocksdb/rocksdb_plugins/zenfs/fs/fs_zenfs.cc: In member function ‘rocksdb::Status rocksdb::ZenFS::MkFS(std::string, uint32_t)’:
/data/mysql-server/percona-8.0/storage/rocksdb/rocksdb_plugins/zenfs/fs/fs_zenfs.cc:1480:32: error: redundant move in return statement [-Werror=redundant-move]
1480 |   if (!s.ok()) return std::move(s);
|                       ~~~~~~~~~^~~
/data/mysql-server/percona-8.0/storage/rocksdb/rocksdb_plugins/zenfs/fs/fs_zenfs.cc:1480:32: note: remove ‘std::move’ call
```
Signed-off-by: Przemyslaw Skibinski <przemyslaw.skibinski@percona.com>

fs: fixed gcc-13 compilation warnings

---

.github/workflows/long-performance.yaml
.github/workflows/mtr-test.yaml
.github/workflows/percona-server-smoke-test.yaml
.github/workflows/rocks-nightly.yaml
.github/workflows/short-performance.yaml
.github/workflows/zbdbench.yaml

Overwriting cron schedules, such that Andreas Hindborg (https://github.com/metaspace) does not get notifications triggered by scheduled workflows that fail.

ci: Overwrite cron schedules on workflows

---

fs/fs_zenfs.h
fs/io_zenfs.h

WritableFile::GetFileSize needs to be imlemented now, so hook it up to make it compilable on latest rocksdb.

fs: fix compile error on latest RocksDB
